[workspace]
resolver = "3"
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
minifb = "0.28.0"
png = "0.18.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
winit = "0.30.12"
wgpu = "28.0.0"
env_logger = "0.11.8"
anyhow = "1.0.100"
pollster = "0.4.0"
log = "0.4.29"
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg"] }
